apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kube-system                
  name: antrea-node    
rules:                 
- apiGroups: [""]      
  resources: ["serviceaccounts"]        
  resourceNames: ["antrea-agent"]       
  verbs: ["get"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list","get"]         
---                    
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding      
metadata:              
  name: read-antrea    
  namespace: kube-system                
subjects:              
- kind: Group          
  name: system:nodes   
  apiGroup: rbac.authorization.k8s.io   
roleRef:               
  kind: Role           
  name: antrea-node    
  apiGroup: rbac.authorization.k8s.io
---          
rules:                
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding      
metadata:              
  name: read-antrea    
  namespace: kube-system                
subjects:              
- kind: Group          
  name: system:nodes   
  apiGroup: rbac.authorization.k8s.io   
roleRef:               
  kind: Role           
  name: antrea-node    
  apiGroup: rbac.authorization.k8s.io      
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding                
metadata:              
  name: read-kubeproxy 
  namespace: kube-system                
subjects:              
- kind: Group          
  name: system:nodes   
  apiGroup: rbac.authorization.k8s.io   
roleRef:               
  kind: ClusterRole    
  name: kubeproxy-node 
  apiGroup: rbac.authorization.k8s.io   
# THIS IS AN EXTRA FILE WERE NOT SURE WHY WE NEED IT BUT IT MAKES THE ANTREA STUFF WORK END TO END
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node:kube-proxy
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node:kube-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node:kube-proxy
subjects:
- kind: Group          
  name: system:nodes   
  apiGroup: rbac.authorization.k8s.io  
