apiVersion: v1
kind: Service
metadata:
  name: service-agn
  labels:
    app: service-agn
spec:
  ports:
    - port: 80
  selector:
    app: service-agn
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-agn
  name: service-agn
spec:
  replicas: 110
  selector:
    matchLabels:
      app: service-agn
  template:
    metadata:
      labels:
        app: service-agn
      name: service-agn
    spec:
     containers:
      - name: aspnet
        image: k8s.gcr.io/e2e-test-images/agnhost:2.21
