apiVersion: v1
kind: Pod
metadata:
  name: test-pod2
  labels:
    role: test-pod2
  namespace: default
spec:
  containers:
    - name: test-pod2
      image: k8s.gcr.io/e2e-test-images/agnhost:2.21
  hostNetwork: false
