release:
  version: ""
providers:
  - name: cluster-api
    url: TANZU_CONFIG_DIR/tkg/providers/cluster-api/v0.3.14/core-components.yaml
    type: CoreProvider
  - name: aws
    url: TANZU_CONFIG_DIR/tkg/providers/infrastructure-aws/v0.6.4/infrastructure-components.yaml
    type: InfrastructureProvider
  - name: vsphere
    url: TANZU_CONFIG_DIR/tkg/providers/infrastructure-vsphere/v0.7.6/infrastructure-components.yaml
    type: InfrastructureProvider
  - name: windows-vsphere
    url: TANZU_CONFIG_DIR/tkg/providers/infrastructure-windows-vsphere/v0.7.6/infrastructure-components.yaml
    type: InfrastructureProvider
  - name: azure
    url: TANZU_CONFIG_DIR/tkg/providers/infrastructure-azure/v0.4.8/infrastructure-components.yaml
    type: InfrastructureProvider
  - name: tkg-service-vsphere
    url: TANZU_CONFIG_DIR/tkg/providers/infrastructure-tkg-service-vsphere/v1.0.0/unused.yaml
    type: InfrastructureProvider
  - name: kubeadm
    url: TANZU_CONFIG_DIR/tkg/providers/bootstrap-kubeadm/v0.3.14/bootstrap-components.yaml
    type: BootstrapProvider
  - name: kubeadm
    url: TANZU_CONFIG_DIR/tkg/providers/control-plane-kubeadm/v0.3.14/control-plane-components.yaml
    type: ControlPlaneProvider
  - name: docker
    url: TANZU_CONFIG_DIR/tkg/providers/infrastructure-docker/v0.3.10/infrastructure-components.yaml
    type: InfrastructureProvider
images:
  all:
    repository: projects-stg.registry.vmware.com/tkg/cluster-api
  cert-manager:
    repository: projects-stg.registry.vmware.com/tkg
    tag: v0.16.1_vmware.1